# -*- coding: utf-8 -*-
"""
Created on Mon May 13 15:53:20 2024
@author: anais
"""
#Import des Pokemons
from pokemons import liste_pokemon
    
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QDialog
from PyQt5.QtCore import Qt
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1460, 1000)
        
        if liste_pokemon[0].rencontre == True :
            self.p1 = QtWidgets.QLabel(Dialog)
            self.p1.setGeometry(QtCore.QRect(10, 0, 91, 101))
            self.p1.setText("")
            self.p1.setTextFormat(QtCore.Qt.RichText)
            self.p1.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Bulbasaur_F.png"))
            self.p1.setObjectName("p1")
        if liste_pokemon[1].rencontre == True :
            self.p2 = QtWidgets.QLabel(Dialog)
            self.p2.setGeometry(QtCore.QRect(100, 0, 91, 101))
            self.p2.setText("")
            self.p2.setTextFormat(QtCore.Qt.RichText)
            self.p2.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Ivysaur_F.png"))
            self.p2.setObjectName("p2")
        if liste_pokemon[2].rencontre == True :
            self.p3 = QtWidgets.QLabel(Dialog)
            self.p3.setGeometry(QtCore.QRect(190, 0, 91, 101))
            self.p3.setText("")
            self.p3.setTextFormat(QtCore.Qt.RichText)
            self.p3.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Venusaur_F.png"))
            self.p3.setObjectName("p3")
        if liste_pokemon[3].rencontre == True :
            self.p4 = QtWidgets.QLabel(Dialog)
            self.p4.setGeometry(QtCore.QRect(280, 0, 91, 101))
            self.p4.setText("")
            self.p4.setTextFormat(QtCore.Qt.RichText)
            self.p4.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Charmander_F.png"))
            self.p4.setObjectName("p4")
        if liste_pokemon[4].rencontre == True :
            self.p5 = QtWidgets.QLabel(Dialog)
            self.p5.setGeometry(QtCore.QRect(370, 0, 91, 101))
            self.p5.setText("")
            self.p5.setTextFormat(QtCore.Qt.RichText)
            self.p5.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Charmeleon_F.png"))
            self.p5.setObjectName("p5")
        if liste_pokemon[5].rencontre == True :
            self.p6 = QtWidgets.QLabel(Dialog)
            self.p6.setGeometry(QtCore.QRect(460, 0, 91, 101))
            self.p6.setText("")
            self.p6.setTextFormat(QtCore.Qt.RichText)
            self.p6.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Charizard_F.png"))
            self.p6.setObjectName("p6")
        if liste_pokemon[6].rencontre == True :
            self.p7 = QtWidgets.QLabel(Dialog)
            self.p7.setGeometry(QtCore.QRect(550, 0, 91, 101))
            self.p7.setText("")
            self.p7.setTextFormat(QtCore.Qt.RichText)
            self.p7.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Squirtle_F.png"))
            self.p7.setObjectName("p7")   
        if liste_pokemon[7].rencontre == True :
            self.p8 = QtWidgets.QLabel(Dialog)
            self.p8.setGeometry(QtCore.QRect(640, 0, 91, 101))
            self.p8.setText("")
            self.p8.setTextFormat(QtCore.Qt.RichText)
            self.p8.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Wartortle_F.png"))
            self.p8.setObjectName("p8")
        if liste_pokemon[8].rencontre == True :
            self.p9 = QtWidgets.QLabel(Dialog)
            self.p9.setGeometry(QtCore.QRect(730, 0, 91, 101))
            self.p9.setText("")
            self.p9.setTextFormat(QtCore.Qt.RichText)
            self.p9.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Blastoise_F.png"))
            self.p9.setObjectName("p9")
        if liste_pokemon[9].rencontre == True :
            self.p10 = QtWidgets.QLabel(Dialog)
            self.p10.setGeometry(QtCore.QRect(820, 0, 91, 101))
            self.p10.setText("")
            self.p10.setTextFormat(QtCore.Qt.RichText)
            self.p10.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Caterpie_F.png"))
            self.p10.setObjectName("p10")
        if liste_pokemon[10].rencontre == True :
            self.p11 = QtWidgets.QLabel(Dialog)
            self.p11.setGeometry(QtCore.QRect(910, 0, 91, 101))
            self.p11.setText("")
            self.p11.setTextFormat(QtCore.Qt.RichText)
            self.p11.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Metapod_F.png"))
            self.p11.setObjectName("p11")
        if liste_pokemon[11].rencontre == True :
            self.p12 = QtWidgets.QLabel(Dialog)
            self.p12.setGeometry(QtCore.QRect(1000, 0, 91, 101))
            self.p12.setText("")
            self.p12.setTextFormat(QtCore.Qt.RichText)
            self.p12.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Butterfree_F.png"))
            self.p12.setObjectName("p12")
        if liste_pokemon[12].rencontre == True :
            self.p13 = QtWidgets.QLabel(Dialog)
            self.p13.setGeometry(QtCore.QRect(1090, 0, 91, 101))
            self.p13.setText("")
            self.p13.setTextFormat(QtCore.Qt.RichText)
            self.p13.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Weedle_F.png"))
            self.p13.setObjectName("p13")
        if liste_pokemon[13].rencontre == True :
            self.p14 = QtWidgets.QLabel(Dialog)
            self.p14.setGeometry(QtCore.QRect(1180, 0, 91, 101))
            self.p14.setText("")
            self.p14.setTextFormat(QtCore.Qt.RichText)
            self.p14.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Kakuna_F.png"))
            self.p14.setObjectName("p14")
        if liste_pokemon[14].rencontre == True :
            self.p15 = QtWidgets.QLabel(Dialog)
            self.p15.setGeometry(QtCore.QRect(1270, 0, 91, 101))
            self.p15.setText("")
            self.p15.setTextFormat(QtCore.Qt.RichText)
            self.p15.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Beedrill_F.png"))
            self.p15.setObjectName("p15")
        if liste_pokemon[15].rencontre == True :
            self.p16 = QtWidgets.QLabel(Dialog)
            self.p16.setGeometry(QtCore.QRect(10, 100, 91, 101))
            self.p16.setText("")
            self.p16.setTextFormat(QtCore.Qt.RichText)
            self.p16.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Pidgey_F.png"))
            self.p16.setObjectName("p16")
        if liste_pokemon[16].rencontre == True :
            self.p17 = QtWidgets.QLabel(Dialog)
            self.p17.setGeometry(QtCore.QRect(100, 100, 91, 101))
            self.p17.setText("")
            self.p17.setTextFormat(QtCore.Qt.RichText)
            self.p17.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Pidgeotto_F.png"))
            self.p17.setObjectName("p17")
        if liste_pokemon[17].rencontre == True :
            self.p18 = QtWidgets.QLabel(Dialog)
            self.p18.setGeometry(QtCore.QRect(190, 100, 91, 101))
            self.p18.setText("")
            self.p18.setTextFormat(QtCore.Qt.RichText)
            self.p18.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Pidgeot_F.png"))
            self.p18.setObjectName("p18")
        if liste_pokemon[18].rencontre == True :
            self.p19 = QtWidgets.QLabel(Dialog)
            self.p19.setGeometry(QtCore.QRect(280, 100, 91, 101))
            self.p19.setText("")
            self.p19.setTextFormat(QtCore.Qt.RichText)
            self.p19.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Rattata_F.png"))
            self.p19.setObjectName("p19")
        if liste_pokemon[19].rencontre == True :
            self.p20 = QtWidgets.QLabel(Dialog)
            self.p20.setGeometry(QtCore.QRect(370, 100, 91, 101))
            self.p20.setText("")
            self.p20.setTextFormat(QtCore.Qt.RichText)
            self.p20.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Raticate_F.png"))
            self.p20.setObjectName("p20")
        if liste_pokemon[20].rencontre == True :
            self.p21 = QtWidgets.QLabel(Dialog)
            self.p21.setGeometry(QtCore.QRect(460, 100, 91, 101))
            self.p21.setText("")
            self.p21.setTextFormat(QtCore.Qt.RichText)
            self.p21.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Spearow_F.png"))
            self.p21.setObjectName("p21")
        if liste_pokemon[21].rencontre == True :
            self.p22 = QtWidgets.QLabel(Dialog)
            self.p22.setGeometry(QtCore.QRect(550, 100, 91, 101))
            self.p22.setText("")
            self.p22.setTextFormat(QtCore.Qt.RichText)
            self.p22.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Fearow_F.png"))
            self.p22.setObjectName("p22")
        if liste_pokemon[22].rencontre == True :
            self.p23 = QtWidgets.QLabel(Dialog)
            self.p23.setGeometry(QtCore.QRect(640, 100, 91, 101))
            self.p23.setText("")
            self.p23.setTextFormat(QtCore.Qt.RichText)
            self.p23.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Ekans_F.png"))
            self.p23.setObjectName("p23")
        if liste_pokemon[23].rencontre == True :
            self.p24 = QtWidgets.QLabel(Dialog)
            self.p24.setGeometry(QtCore.QRect(730, 100, 91, 101))
            self.p24.setText("")
            self.p24.setTextFormat(QtCore.Qt.RichText)
            self.p24.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Arbok_F.png"))
            self.p24.setObjectName("p24")
        if liste_pokemon[24].rencontre == True :
            self.p25 = QtWidgets.QLabel(Dialog)
            self.p25.setGeometry(QtCore.QRect(820, 100, 91, 101))
            self.p25.setText("")
            self.p25.setTextFormat(QtCore.Qt.RichText)
            self.p25.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Pikachu_F.png"))
            self.p25.setObjectName("p25")
        if liste_pokemon[25].rencontre == True :
            self.p26 = QtWidgets.QLabel(Dialog)
            self.p26.setGeometry(QtCore.QRect(910, 100, 91, 101))
            self.p26.setText("")
            self.p26.setTextFormat(QtCore.Qt.RichText)
            self.p26.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Raichu_F.png"))
            self.p26.setObjectName("p26")
        if liste_pokemon[26].rencontre == True :
            self.p27 = QtWidgets.QLabel(Dialog)
            self.p27.setGeometry(QtCore.QRect(1000, 100, 91, 101))
            self.p27.setText("")
            self.p27.setTextFormat(QtCore.Qt.RichText)
            self.p27.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Sandshrew_F.png"))
            self.p27.setObjectName("p27")
        if liste_pokemon[27].rencontre == True :
            self.p28 = QtWidgets.QLabel(Dialog)
            self.p28.setGeometry(QtCore.QRect(1090, 100, 91, 101))
            self.p28.setText("")
            self.p28.setTextFormat(QtCore.Qt.RichText)
            self.p28.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Sandslash_F.png"))
            self.p28.setObjectName("p28")
        if liste_pokemon[28].rencontre == True :
            self.p29 = QtWidgets.QLabel(Dialog)
            self.p29.setGeometry(QtCore.QRect(1180, 100, 91, 101))
            self.p29.setText("")
            self.p29.setTextFormat(QtCore.Qt.RichText)
            self.p29.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidoran♀_F.png"))
            self.p29.setObjectName("p29")
        if liste_pokemon[29].rencontre == True :
            self.p30 = QtWidgets.QLabel(Dialog)
            self.p30.setGeometry(QtCore.QRect(1270, 100, 91, 101))
            self.p30.setText("")
            self.p30.setTextFormat(QtCore.Qt.RichText)
            self.p30.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidorina_F.png"))
            self.p30.setObjectName("p30")
        if liste_pokemon[30].rencontre == True :
            self.p31 = QtWidgets.QLabel(Dialog)
            self.p31.setGeometry(QtCore.QRect(10, 200, 91, 101))
            self.p31.setText("")
            self.p31.setTextFormat(QtCore.Qt.RichText)
            self.p31.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidoqueen_F.png"))
            self.p31.setObjectName("p31")
        if liste_pokemon[31].rencontre == True :
            self.p32 = QtWidgets.QLabel(Dialog)
            self.p32.setGeometry(QtCore.QRect(100, 200, 91, 101))
            self.p32.setText("")
            self.p32.setTextFormat(QtCore.Qt.RichText)
            self.p32.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidoran♂_F.png"))
            self.p32.setObjectName("p32")
        if liste_pokemon[32].rencontre == True :
            self.p33 = QtWidgets.QLabel(Dialog)
            self.p33.setGeometry(QtCore.QRect(190, 200, 91, 101))
            self.p33.setText("")
            self.p33.setTextFormat(QtCore.Qt.RichText)
            self.p33.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidorino_F.png"))
            self.p33.setObjectName("p33")
        if liste_pokemon[33].rencontre == True :
            self.p34 = QtWidgets.QLabel(Dialog)
            self.p34.setGeometry(QtCore.QRect(280, 200, 91, 101))
            self.p34.setText("")
            self.p34.setTextFormat(QtCore.Qt.RichText)
            self.p34.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidoking_F.png"))
            self.p34.setObjectName("p34")
        if liste_pokemon[34].rencontre == True :
            self.p35 = QtWidgets.QLabel(Dialog)
            self.p35.setGeometry(QtCore.QRect(370, 200, 91, 101))
            self.p35.setText("")
            self.p35.setTextFormat(QtCore.Qt.RichText)
            self.p35.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Clefairy_F.png"))
            self.p35.setObjectName("p35")
        if liste_pokemon[35].rencontre == True :
            self.p36 = QtWidgets.QLabel(Dialog)
            self.p36.setGeometry(QtCore.QRect(460, 200, 91, 101))
            self.p36.setText("")
            self.p36.setTextFormat(QtCore.Qt.RichText)
            self.p36.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Clefable_F.png"))
            self.p36.setObjectName("p36")
        if liste_pokemon[36].rencontre == True :
            self.p37 = QtWidgets.QLabel(Dialog)
            self.p37.setGeometry(QtCore.QRect(550, 200, 91, 101))
            self.p37.setText("")
            self.p37.setTextFormat(QtCore.Qt.RichText)
            self.p37.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Vulpix_F.png"))
            self.p37.setObjectName("p37")
        if liste_pokemon[37].rencontre == True :
            self.p38 = QtWidgets.QLabel(Dialog)
            self.p38.setGeometry(QtCore.QRect(640, 200, 91, 101))
            self.p38.setText("")
            self.p38.setTextFormat(QtCore.Qt.RichText)
            self.p38.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Ninetales_F.png"))
            self.p38.setObjectName("38")
        if liste_pokemon[38].rencontre == True :
            self.p39 = QtWidgets.QLabel(Dialog)
            self.p39.setGeometry(QtCore.QRect(730, 200, 91, 101))
            self.p39.setText("")
            self.p39.setTextFormat(QtCore.Qt.RichText)
            self.p39.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Jigglypuff_F.png"))
            self.p39.setObjectName("39")
        if liste_pokemon[39].rencontre == True :
            self.p40 = QtWidgets.QLabel(Dialog)
            self.p40.setGeometry(QtCore.QRect(820, 200, 91, 101))
            self.p40.setText("")
            self.p40.setTextFormat(QtCore.Qt.RichText)
            self.p40.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Wigglytuff_F.png"))
            self.p40.setObjectName("p40")
        if liste_pokemon[40].rencontre == True : 
            self.p41 = QtWidgets.QLabel(Dialog)
            self.p41.setGeometry(QtCore.QRect(910, 200, 91, 101))
            self.p41.setText("")
            self.p41.setTextFormat(QtCore.Qt.RichText)
            self.p41.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Zubat_F.png"))
            self.p41.setObjectName("p41")
        if liste_pokemon[41].rencontre == True :  
            self.p42 = QtWidgets.QLabel(Dialog)
            self.p42.setGeometry(QtCore.QRect(1000, 200, 91, 101))
            self.p42.setText("")
            self.p42.setTextFormat(QtCore.Qt.RichText)
            self.p42.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Golbat_F.png"))
            self.p42.setObjectName("p42")
        if liste_pokemon[42].rencontre == True :
            self.p43 = QtWidgets.QLabel(Dialog)
            self.p43.setGeometry(QtCore.QRect(1090, 200, 91, 101))
            self.p43.setText("")
            self.p43.setTextFormat(QtCore.Qt.RichText)
            self.p43.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Oddish_F.png"))
            self.p43.setObjectName("p43")
        if liste_pokemon[43].rencontre == True :
            self.p44 = QtWidgets.QLabel(Dialog)
            self.p44.setGeometry(QtCore.QRect(1180, 200, 91, 101))
            self.p44.setText("")
            self.p44.setTextFormat(QtCore.Qt.RichText)
            self.p44.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Gloom_F.png"))
            self.p44.setObjectName("p44")
        if liste_pokemon[44].rencontre == True :
            self.p45 = QtWidgets.QLabel(Dialog)
            self.p45.setGeometry(QtCore.QRect(1270, 200, 91, 101))
            self.p45.setText("")
            self.p45.setTextFormat(QtCore.Qt.RichText)
            self.p45.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Vileplume_F.png"))
            self.p45.setObjectName("p45")
        if liste_pokemon[45].rencontre == True :
            self.p46 = QtWidgets.QLabel(Dialog)
            self.p46.setGeometry(QtCore.QRect(10, 300, 91, 101))
            self.p46.setText("")
            self.p46.setTextFormat(QtCore.Qt.RichText)
            self.p46.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Paras_F.png"))
            self.p46.setObjectName("p46")
        if liste_pokemon[46].rencontre == True :
            self.p47 = QtWidgets.QLabel(Dialog)
            self.p47.setGeometry(QtCore.QRect(100, 300, 91, 101))
            self.p47.setText("")
            self.p47.setTextFormat(QtCore.Qt.RichText)
            self.p47.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Parasect_F.png"))
            self.p47.setObjectName("p47")
        if liste_pokemon[47].rencontre == True :
            self.p48 = QtWidgets.QLabel(Dialog)
            self.p48.setGeometry(QtCore.QRect(190, 300, 91, 101))
            self.p48.setText("")
            self.p48.setTextFormat(QtCore.Qt.RichText)
            self.p48.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Venonat_F.png"))
            self.p48.setObjectName("p48")
        if liste_pokemon[48].rencontre == True :
            self.p49 = QtWidgets.QLabel(Dialog)
            self.p49.setGeometry(QtCore.QRect(280, 300, 91, 101))
            self.p49.setText("")
            self.p49.setTextFormat(QtCore.Qt.RichText)
            self.p49.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Venomoth_F.png"))
            self.p49.setObjectName("p49")
        if liste_pokemon[49].rencontre == True :
            self.p50 = QtWidgets.QLabel(Dialog)
            self.p50.setGeometry(QtCore.QRect(370, 300, 91, 101))
            self.p50.setText("")
            self.p50.setTextFormat(QtCore.Qt.RichText)
            self.p50.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Diglett_F.png"))
            self.p50.setObjectName("p50")
        if liste_pokemon[50].rencontre == True :
            self.p51 = QtWidgets.QLabel(Dialog)
            self.p51.setGeometry(QtCore.QRect(460, 300, 91, 101))
            self.p51.setText("")
            self.p51.setTextFormat(QtCore.Qt.RichText)
            self.p51.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Dugtrio_F.png"))
            self.p51.setObjectName("p51")
        if liste_pokemon[51].rencontre == True :
            self.p52 = QtWidgets.QLabel(Dialog)
            self.p52.setGeometry(QtCore.QRect(550, 300, 91, 101))
            self.p52.setText("")
            self.p52.setTextFormat(QtCore.Qt.RichText)
            self.p52.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Meowth_F.png"))
            self.p52.setObjectName("p52")
        if liste_pokemon[52].rencontre == True :
            self.p53 = QtWidgets.QLabel(Dialog)
            self.p53.setGeometry(QtCore.QRect(640, 300, 91, 101))
            self.p53.setText("")
            self.p53.setTextFormat(QtCore.Qt.RichText)
            self.p53.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Persian_F.png"))
            self.p53.setObjectName("p53")
        if liste_pokemon[53].rencontre == True :
            self.p54 = QtWidgets.QLabel(Dialog)
            self.p54.setGeometry(QtCore.QRect(730, 300, 91, 101))
            self.p54.setText("")
            self.p54.setTextFormat(QtCore.Qt.RichText)
            self.p54.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Psyduck_F.png"))
            self.p54.setObjectName("p54")
        if liste_pokemon[54].rencontre == True :
            self.p55 = QtWidgets.QLabel(Dialog)
            self.p55.setGeometry(QtCore.QRect(820, 300, 91, 101))
            self.p55.setText("")
            self.p55.setTextFormat(QtCore.Qt.RichText)
            self.p55.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Golduck_F.png"))
            self.p55.setObjectName("p55")
        if liste_pokemon[55].rencontre == True :
            self.p56 = QtWidgets.QLabel(Dialog)
            self.p56.setGeometry(QtCore.QRect(910, 300, 91, 101))
            self.p56.setText("")
            self.p56.setTextFormat(QtCore.Qt.RichText)
            self.p56.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Mankey_F.png"))
            self.p56.setObjectName("p56")
        if liste_pokemon[56].rencontre == True :
            self.p57 = QtWidgets.QLabel(Dialog)
            self.p57.setGeometry(QtCore.QRect(1000, 300, 91, 101))
            self.p57.setText("")
            self.p57.setTextFormat(QtCore.Qt.RichText)
            self.p57.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Primeape_F.png"))
            self.p57.setObjectName("p57")
        if liste_pokemon[57].rencontre == True :
            self.p58 = QtWidgets.QLabel(Dialog)
            self.p58.setGeometry(QtCore.QRect(1090, 300, 91, 101))
            self.p58.setText("")
            self.p58.setTextFormat(QtCore.Qt.RichText)
            self.p58.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Growlithe_F.png"))
            self.p58.setObjectName("p58")
        if liste_pokemon[58].rencontre == True :
            self.p59 = QtWidgets.QLabel(Dialog)
            self.p59.setGeometry(QtCore.QRect(1180, 300, 91, 101))
            self.p59.setText("")
            self.p59.setTextFormat(QtCore.Qt.RichText)
            self.p59.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Arcanine_F.png"))
            self.p59.setObjectName("p59")
        if liste_pokemon[59].rencontre == True :
            self.p60 = QtWidgets.QLabel(Dialog)
            self.p60.setGeometry(QtCore.QRect(1270, 300, 91, 101))
            self.p60.setText("")
            self.p60.setTextFormat(QtCore.Qt.RichText)
            self.p60.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Poliwag_F.png"))
            self.p60.setObjectName("p60")
        if liste_pokemon[60].rencontre == True :
            self.p61 = QtWidgets.QLabel(Dialog)
            self.p61.setGeometry(QtCore.QRect(10, 400, 91, 101))
            self.p61.setText("")
            self.p61.setTextFormat(QtCore.Qt.RichText)
            self.p61.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Poliwhirl_F.png"))
            self.p61.setObjectName("p61")
        if liste_pokemon[61].rencontre == True :
            self.p62 = QtWidgets.QLabel(Dialog)
            self.p62.setGeometry(QtCore.QRect(100, 400, 91, 101))
            self.p62.setText("")
            self.p62.setTextFormat(QtCore.Qt.RichText)
            self.p62.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Poliwrath_F.png"))
            self.p62.setObjectName("p62")
        if liste_pokemon[62].rencontre == True :
            self.p63 = QtWidgets.QLabel(Dialog)
            self.p63.setGeometry(QtCore.QRect(190, 400, 91, 101))
            self.p63.setText("")
            self.p63.setTextFormat(QtCore.Qt.RichText)
            self.p63.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Abra_F.png"))
            self.p63.setObjectName("p63")
        if liste_pokemon[63].rencontre == True :
            self.p64 = QtWidgets.QLabel(Dialog)
            self.p64.setGeometry(QtCore.QRect(280, 400, 91, 101))
            self.p64.setText("")
            self.p64.setTextFormat(QtCore.Qt.RichText)
            self.p64.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Kadabra_F.png"))
            self.p64.setObjectName("p64")
        if liste_pokemon[64].rencontre == True :
            self.p65 = QtWidgets.QLabel(Dialog)
            self.p65.setGeometry(QtCore.QRect(370, 400, 91, 101))
            self.p65.setText("")
            self.p65.setTextFormat(QtCore.Qt.RichText)
            self.p65.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Alakazam_F.png"))
            self.p65.setObjectName("p65")
        if liste_pokemon[65].rencontre == True :
            self.p66 = QtWidgets.QLabel(Dialog)
            self.p66.setGeometry(QtCore.QRect(460, 400, 91, 101))
            self.p66.setText("")
            self.p66.setTextFormat(QtCore.Qt.RichText)
            self.p66.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Machop_F.png"))
            self.p66.setObjectName("p66")
        if liste_pokemon[66].rencontre == True :
            self.p67 = QtWidgets.QLabel(Dialog)
            self.p67.setGeometry(QtCore.QRect(550, 400, 91, 101))
            self.p67.setText("")
            self.p67.setTextFormat(QtCore.Qt.RichText)
            self.p67.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Machoke_F.png"))
            self.p67.setObjectName("p67")
        if liste_pokemon[67].rencontre == True :
            self.p68 = QtWidgets.QLabel(Dialog)
            self.p68.setGeometry(QtCore.QRect(640, 400, 91, 101))
            self.p68.setText("")
            self.p68.setTextFormat(QtCore.Qt.RichText)
            self.p68.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Machamp_F.png"))
            self.p68.setObjectName("p68")
        if liste_pokemon[68].rencontre == True :
            self.p69 = QtWidgets.QLabel(Dialog)
            self.p69.setGeometry(QtCore.QRect(730, 400, 91, 101))
            self.p69.setText("")
            self.p69.setTextFormat(QtCore.Qt.RichText)
            self.p69.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Bellsprout_F.png"))
            self.p69.setObjectName("p69")
        if liste_pokemon[69].rencontre == True :
            self.p70 = QtWidgets.QLabel(Dialog)
            self.p70.setGeometry(QtCore.QRect(820, 400, 91, 101))
            self.p70.setText("")
            self.p70.setTextFormat(QtCore.Qt.RichText)
            self.p70.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Weepinbell_F.png"))
            self.p70.setObjectName("p70")
        if liste_pokemon[70].rencontre == True :
            self.p71 = QtWidgets.QLabel(Dialog)
            self.p71.setGeometry(QtCore.QRect(910, 400, 91, 101))
            self.p71.setText("")
            self.p71.setTextFormat(QtCore.Qt.RichText)
            self.p71.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Victreebel_F.png"))
            self.p71.setObjectName("p71")
        if liste_pokemon[71].rencontre == True :
            self.p72 = QtWidgets.QLabel(Dialog)
            self.p72.setGeometry(QtCore.QRect(1000, 400, 91, 101))
            self.p72.setText("")
            self.p72.setTextFormat(QtCore.Qt.RichText)
            self.p72.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Tentacool_F.png"))
            self.p72.setObjectName("p72")
        if liste_pokemon[72].rencontre == True :
            self.p73 = QtWidgets.QLabel(Dialog)
            self.p73.setGeometry(QtCore.QRect(1090, 400, 91, 101))
            self.p73.setText("")
            self.p73.setTextFormat(QtCore.Qt.RichText)
            self.p73.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Tentacruel_F.png"))
            self.p73.setObjectName("p73")
        if liste_pokemon[73].rencontre == True :
            self.p74 = QtWidgets.QLabel(Dialog)
            self.p74.setGeometry(QtCore.QRect(1180, 400, 91, 101))
            self.p74.setText("")
            self.p74.setTextFormat(QtCore.Qt.RichText)
            self.p74.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Geodude_F.png"))
            self.p74.setObjectName("p74")
        if liste_pokemon[74].rencontre == True :
            self.p75 = QtWidgets.QLabel(Dialog)
            self.p75.setGeometry(QtCore.QRect(1270, 400, 91, 101))
            self.p75.setText("")
            self.p75.setTextFormat(QtCore.Qt.RichText)
            self.p75.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Graveler_F.png"))
            self.p75.setObjectName("p75")
        if liste_pokemon[75].rencontre == True :
            self.p76 = QtWidgets.QLabel(Dialog)
            self.p76.setGeometry(QtCore.QRect(10, 500, 91, 101))
            self.p76.setText("")
            self.p76.setTextFormat(QtCore.Qt.RichText)
            self.p76.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Golem_F.png"))
            self.p76.setObjectName("p76")
        if liste_pokemon[76].rencontre == True :
            self.p77 = QtWidgets.QLabel(Dialog)
            self.p77.setGeometry(QtCore.QRect(100, 500, 91, 101))
            self.p77.setText("")
            self.p77.setTextFormat(QtCore.Qt.RichText)
            self.p77.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Ponyta_F.png"))
            self.p77.setObjectName("p77")
        if liste_pokemon[77].rencontre == True :
            self.p78 = QtWidgets.QLabel(Dialog)
            self.p78.setGeometry(QtCore.QRect(190, 500, 91, 101))
            self.p78.setText("")
            self.p78.setTextFormat(QtCore.Qt.RichText)
            self.p78.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Rapidash_F.png"))
            self.p78.setObjectName("p78")
        if liste_pokemon[78].rencontre == True :
            self.p79 = QtWidgets.QLabel(Dialog)
            self.p79.setGeometry(QtCore.QRect(280, 500, 91, 101))
            self.p79.setText("")
            self.p79.setTextFormat(QtCore.Qt.RichText)
            self.p79.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Slowpoke_F.png"))
            self.p79.setObjectName("p79")
        if liste_pokemon[79].rencontre == True :
            self.p80 = QtWidgets.QLabel(Dialog)
            self.p80.setGeometry(QtCore.QRect(370, 500, 91, 101))
            self.p80.setText("")
            self.p80.setTextFormat(QtCore.Qt.RichText)
            self.p80.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Slowbro_F.png"))
            self.p80.setObjectName("p80")
        if liste_pokemon[80].rencontre == True :
            self.p81 = QtWidgets.QLabel(Dialog)
            self.p81.setGeometry(QtCore.QRect(460, 500, 91, 101))
            self.p81.setText("")
            self.p81.setTextFormat(QtCore.Qt.RichText)
            self.p81.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Magnemite_F.png"))
            self.p81.setObjectName("p81")
        if liste_pokemon[81].rencontre == True :
            self.p82 = QtWidgets.QLabel(Dialog)
            self.p82.setGeometry(QtCore.QRect(550, 500, 91, 101))
            self.p82.setText("")
            self.p82.setTextFormat(QtCore.Qt.RichText)
            self.p82.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Magneton_F.png"))
            self.p82.setObjectName("p82")
        if liste_pokemon[82].rencontre == True :
            self.p83 = QtWidgets.QLabel(Dialog)
            self.p83.setGeometry(QtCore.QRect(640, 500, 91, 101))
            self.p83.setText("")
            self.p83.setTextFormat(QtCore.Qt.RichText)
            self.p83.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Farfetch'd_F.png"))
            self.p83.setObjectName("p83")
        if liste_pokemon[83].rencontre == True :
            self.p84 = QtWidgets.QLabel(Dialog)
            self.p84.setGeometry(QtCore.QRect(730, 500, 91, 101))
            self.p84.setText("")
            self.p84.setTextFormat(QtCore.Qt.RichText)
            self.p84.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Doduo_F.png"))
            self.p84.setObjectName("p84")
        if liste_pokemon[84].rencontre == True :
            self.p85 = QtWidgets.QLabel(Dialog)
            self.p85.setGeometry(QtCore.QRect(820, 500, 91, 101))
            self.p85.setText("")
            self.p85.setTextFormat(QtCore.Qt.RichText)
            self.p85.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Dodrio_F.png"))
            self.p85.setObjectName("p85")
        if liste_pokemon[85].rencontre == True :
            self.p86 = QtWidgets.QLabel(Dialog)
            self.p86.setGeometry(QtCore.QRect(910, 500, 91, 101))
            self.p86.setText("")
            self.p86.setTextFormat(QtCore.Qt.RichText)
            self.p86.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Seel_F.png"))
            self.p86.setObjectName("p86")
        if liste_pokemon[86].rencontre == True :
            self.p87 = QtWidgets.QLabel(Dialog)
            self.p87.setGeometry(QtCore.QRect(1000, 500, 91, 101))
            self.p87.setText("")
            self.p87.setTextFormat(QtCore.Qt.RichText)
            self.p87.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Dewgong_F.png"))
            self.p87.setObjectName("p87")
        if liste_pokemon[87].rencontre == True :
            self.p88 = QtWidgets.QLabel(Dialog)
            self.p88.setGeometry(QtCore.QRect(1090, 500, 91, 101))
            self.p88.setText("")
            self.p88.setTextFormat(QtCore.Qt.RichText)
            self.p88.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Grimer_F.png"))
            self.p88.setObjectName("p88")
        if liste_pokemon[88].rencontre == True :
            self.p89 = QtWidgets.QLabel(Dialog)
            self.p89.setGeometry(QtCore.QRect(1180, 500, 91, 101))
            self.p89.setText("")
            self.p89.setTextFormat(QtCore.Qt.RichText)
            self.p89.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Muk_F.png"))
            self.p89.setObjectName("p89")
        if liste_pokemon[89].rencontre == True :
            self.p90 = QtWidgets.QLabel(Dialog)
            self.p90.setGeometry(QtCore.QRect(1270, 500, 91, 101))
            self.p90.setText("")
            self.p90.setTextFormat(QtCore.Qt.RichText)
            self.p90.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Shellder_F.png"))
            self.p90.setObjectName("p90")
        if liste_pokemon[90].rencontre == True :
            self.p91 = QtWidgets.QLabel(Dialog)
            self.p91.setGeometry(QtCore.QRect(10, 600, 91, 101))
            self.p91.setText("")
            self.p91.setTextFormat(QtCore.Qt.RichText)
            self.p91.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Cloyster_F.png"))
            self.p91.setObjectName("p91")
        if liste_pokemon[91].rencontre == True :
            self.p92 = QtWidgets.QLabel(Dialog)
            self.p92.setGeometry(QtCore.QRect(100, 600, 91, 101))
            self.p92.setText("")
            self.p92.setTextFormat(QtCore.Qt.RichText)
            self.p92.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Gastly_F.png"))
            self.p92.setObjectName("p92")
        if liste_pokemon[92].rencontre == True :
            self.p93 = QtWidgets.QLabel(Dialog)
            self.p93.setGeometry(QtCore.QRect(190, 600, 91, 101))
            self.p93.setText("")
            self.p93.setTextFormat(QtCore.Qt.RichText)
            self.p93.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Haunter_F.png"))
            self.p93.setObjectName("p93")
        if liste_pokemon[93].rencontre == True :
            self.p94 = QtWidgets.QLabel(Dialog)
            self.p94.setGeometry(QtCore.QRect(280, 600, 91, 101))
            self.p94.setText("")
            self.p94.setTextFormat(QtCore.Qt.RichText)
            self.p94.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Gengar_F.png"))
            self.p94.setObjectName("p94")
        if liste_pokemon[94].rencontre == True :
            self.p95 = QtWidgets.QLabel(Dialog)
            self.p95.setGeometry(QtCore.QRect(370, 600, 91, 101))
            self.p95.setText("")
            self.p95.setTextFormat(QtCore.Qt.RichText)
            self.p95.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Onix_F.png"))
            self.p95.setObjectName("p95")
        if liste_pokemon[95].rencontre == True :
            self.p96 = QtWidgets.QLabel(Dialog)
            self.p96.setGeometry(QtCore.QRect(460, 600, 91, 101))
            self.p96.setText("")
            self.p96.setTextFormat(QtCore.Qt.RichText)
            self.p96.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Drowzee_F.png"))
            self.p96.setObjectName("p96")
        if liste_pokemon[96].rencontre == True :
            self.p97 = QtWidgets.QLabel(Dialog)
            self.p97.setGeometry(QtCore.QRect(550, 600, 91, 101))
            self.p97.setText("")
            self.p97.setTextFormat(QtCore.Qt.RichText)
            self.p97.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Hypno_F.png"))
            self.p97.setObjectName("p97")
        if liste_pokemon[97].rencontre == True :
            self.p98 = QtWidgets.QLabel(Dialog)
            self.p98.setGeometry(QtCore.QRect(640, 600, 91, 101))
            self.p98.setText("")
            self.p98.setTextFormat(QtCore.Qt.RichText)
            self.p98.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Krabby_F.png"))
            self.p98.setObjectName("p98")
        if liste_pokemon[98].rencontre == True :
            self.p99 = QtWidgets.QLabel(Dialog)
            self.p99.setGeometry(QtCore.QRect(730, 600, 91, 101))
            self.p99.setText("")
            self.p99.setTextFormat(QtCore.Qt.RichText)
            self.p99.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Kingler_F.png"))
            self.p99.setObjectName("p99")
        if liste_pokemon[99].rencontre == True :
            self.p100 = QtWidgets.QLabel(Dialog)
            self.p100.setGeometry(QtCore.QRect(820, 600, 91, 101))
            self.p100.setText("")
            self.p100.setTextFormat(QtCore.Qt.RichText)
            self.p100.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Voltorb_F.png"))
            self.p100.setObjectName("p100")
        if liste_pokemon[100].rencontre == True :
            self.p101 = QtWidgets.QLabel(Dialog)
            self.p101.setGeometry(QtCore.QRect(910, 600, 91, 101))
            self.p101.setText("")
            self.p101.setTextFormat(QtCore.Qt.RichText)
            self.p101.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Electrode_F.png"))
            self.p101.setObjectName("p101")
        if liste_pokemon[101].rencontre == True :
            self.p102 = QtWidgets.QLabel(Dialog)
            self.p102.setGeometry(QtCore.QRect(1000, 600, 91, 101))
            self.p102.setText("")
            self.p102.setTextFormat(QtCore.Qt.RichText)
            self.p102.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Exeggcute_F.png"))
            self.p102.setObjectName("p102")
        if liste_pokemon[102].rencontre == True :
            self.p103 = QtWidgets.QLabel(Dialog)
            self.p103.setGeometry(QtCore.QRect(1090, 600, 91, 101))
            self.p103.setText("")
            self.p103.setTextFormat(QtCore.Qt.RichText)
            self.p103.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Exeggutor_F.png"))
            self.p103.setObjectName("p103")
        if liste_pokemon[103].rencontre == True :
            self.p104 = QtWidgets.QLabel(Dialog)
            self.p104.setGeometry(QtCore.QRect(1180, 600, 91, 101))
            self.p104.setText("")
            self.p104.setTextFormat(QtCore.Qt.RichText)
            self.p104.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Cubone_F.png"))
            self.p104.setObjectName("p104")
        if liste_pokemon[104].rencontre == True :
            self.p105 = QtWidgets.QLabel(Dialog)
            self.p105.setGeometry(QtCore.QRect(1270, 600, 91, 101))
            self.p105.setText("")
            self.p105.setTextFormat(QtCore.Qt.RichText)
            self.p105.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Marowak_F.png"))
            self.p105.setObjectName("p105")
        if liste_pokemon[105].rencontre == True :
            self.p106 = QtWidgets.QLabel(Dialog)
            self.p106.setGeometry(QtCore.QRect(10, 700, 91, 101))
            self.p106.setText("")
            self.p106.setTextFormat(QtCore.Qt.RichText)
            self.p106.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Hitmonlee_F.png"))
            self.p106.setObjectName("p106")
        if liste_pokemon[106].rencontre == True :
            self.p107 = QtWidgets.QLabel(Dialog)
            self.p107.setGeometry(QtCore.QRect(100, 700, 91, 101))
            self.p107.setText("")
            self.p107.setTextFormat(QtCore.Qt.RichText)
            self.p107.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Hitmonchan_F.png"))
            self.p107.setObjectName("p107")
        if liste_pokemon[107].rencontre == True :
            self.p108 = QtWidgets.QLabel(Dialog)
            self.p108.setGeometry(QtCore.QRect(190, 700, 91, 101))
            self.p108.setText("")
            self.p108.setTextFormat(QtCore.Qt.RichText)
            self.p108.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Lickitung_F.png"))
            self.p108.setObjectName("p108")
        if liste_pokemon[108].rencontre == True :
            self.p109 = QtWidgets.QLabel(Dialog)
            self.p109.setGeometry(QtCore.QRect(280, 700, 91, 101))
            self.p109.setText("")
            self.p109.setTextFormat(QtCore.Qt.RichText)
            self.p109.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Koffing_F.png"))
            self.p109.setObjectName("p109")
        if liste_pokemon[109].rencontre == True :
            self.p110 = QtWidgets.QLabel(Dialog)
            self.p110.setGeometry(QtCore.QRect(370, 700, 91, 101))
            self.p110.setText("")
            self.p110.setTextFormat(QtCore.Qt.RichText)
            self.p110.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Weezing_F.png"))
            self.p110.setObjectName("p110")
        if liste_pokemon[110].rencontre == True :
            self.p111 = QtWidgets.QLabel(Dialog)
            self.p111.setGeometry(QtCore.QRect(460, 700, 91, 101))
            self.p111.setText("")
            self.p111.setTextFormat(QtCore.Qt.RichText)
            self.p111.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Rhyhorn_F.png"))
            self.p111.setObjectName("p111")
        if liste_pokemon[111].rencontre == True :
            self.p112 = QtWidgets.QLabel(Dialog)
            self.p112.setGeometry(QtCore.QRect(550, 700, 91, 101))
            self.p112.setText("")
            self.p112.setTextFormat(QtCore.Qt.RichText)
            self.p112.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Rhydon_F.png"))
            self.p112.setObjectName("p112")
        if liste_pokemon[112].rencontre == True :
            self.p113 = QtWidgets.QLabel(Dialog)
            self.p113.setGeometry(QtCore.QRect(640, 700, 91, 101))
            self.p113.setText("")
            self.p113.setTextFormat(QtCore.Qt.RichText)
            self.p113.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Chansey_F.png"))
            self.p113.setObjectName("p113")
        if liste_pokemon[113].rencontre == True :
            self.p114 = QtWidgets.QLabel(Dialog)
            self.p114.setGeometry(QtCore.QRect(730, 700, 91, 101))
            self.p114.setText("")
            self.p114.setTextFormat(QtCore.Qt.RichText)
            self.p114.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Tangela_F.png"))
            self.p114.setObjectName("p114")
        if liste_pokemon[114].rencontre == True :
            self.p115 = QtWidgets.QLabel(Dialog)
            self.p115.setGeometry(QtCore.QRect(820, 700, 91, 101))
            self.p115.setText("")
            self.p115.setTextFormat(QtCore.Qt.RichText)
            self.p115.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Kangaskhan_F.png"))
            self.p115.setObjectName("p115")
        if liste_pokemon[115].rencontre == True :
            self.p116 = QtWidgets.QLabel(Dialog)
            self.p116.setGeometry(QtCore.QRect(910, 700, 91, 101))
            self.p116.setText("")
            self.p116.setTextFormat(QtCore.Qt.RichText)
            self.p116.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Horsea_F.png"))
            self.p116.setObjectName("p116")
        if liste_pokemon[116].rencontre == True :
            self.p117 = QtWidgets.QLabel(Dialog)
            self.p117.setGeometry(QtCore.QRect(1000, 700, 91, 101))
            self.p117.setText("")
            self.p117.setTextFormat(QtCore.Qt.RichText)
            self.p117.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Seadra_F.png"))
            self.p117.setObjectName("p117")
        if liste_pokemon[117].rencontre == True :
            self.p118 = QtWidgets.QLabel(Dialog)
            self.p118.setGeometry(QtCore.QRect(1090, 700, 91, 101))
            self.p118.setText("")
            self.p118.setTextFormat(QtCore.Qt.RichText)
            self.p118.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Goldeen_F.png"))
            self.p118.setObjectName("p118")
        if liste_pokemon[118].rencontre == True :
            self.p119 = QtWidgets.QLabel(Dialog)
            self.p119.setGeometry(QtCore.QRect(1180, 700, 91, 101))
            self.p119.setText("")
            self.p119.setTextFormat(QtCore.Qt.RichText)
            self.p119.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Seaking_F.png"))
            self.p119.setObjectName("p119")
        if liste_pokemon[119].rencontre == True :
            self.p120 = QtWidgets.QLabel(Dialog)
            self.p120.setGeometry(QtCore.QRect(1270, 700, 91, 101))
            self.p120.setText("")
            self.p120.setTextFormat(QtCore.Qt.RichText)
            self.p120.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Staryu_F.png"))
            self.p120.setObjectName("p120")
        if liste_pokemon[120].rencontre == True :
            self.p121 = QtWidgets.QLabel(Dialog)
            self.p121.setGeometry(QtCore.QRect(10, 800, 91, 101))
            self.p121.setText("")
            self.p121.setTextFormat(QtCore.Qt.RichText)
            self.p121.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Starmie_F.png"))
            self.p121.setObjectName("p121")
        if liste_pokemon[121].rencontre == True :
            self.p122 = QtWidgets.QLabel(Dialog)
            self.p122.setGeometry(QtCore.QRect(100, 800, 91, 101))
            self.p122.setText("")
            self.p122.setTextFormat(QtCore.Qt.RichText)
            self.p122.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Mr.Mime_F.png"))
            self.p122.setObjectName("p122")
        if liste_pokemon[122].rencontre == True :
            self.p123 = QtWidgets.QLabel(Dialog)
            self.p123.setGeometry(QtCore.QRect(190, 800, 91, 101))
            self.p123.setText("")
            self.p123.setTextFormat(QtCore.Qt.RichText)
            self.p123.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Scyther_F.png"))
            self.p123.setObjectName("p123")
        if liste_pokemon[123].rencontre == True :
            self.p124 = QtWidgets.QLabel(Dialog)
            self.p124.setGeometry(QtCore.QRect(280, 800, 91, 101))
            self.p124.setText("")
            self.p124.setTextFormat(QtCore.Qt.RichText)
            self.p124.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Jynx_F.png"))
            self.p124.setObjectName("p124")
        if liste_pokemon[124].rencontre == True :
            self.p125 = QtWidgets.QLabel(Dialog)
            self.p125.setGeometry(QtCore.QRect(370, 800, 91, 101))
            self.p125.setText("")
            self.p125.setTextFormat(QtCore.Qt.RichText)
            self.p125.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Electabuzz_F.png"))
            self.p125.setObjectName("p125")
        if liste_pokemon[125].rencontre == True :
            self.p126 = QtWidgets.QLabel(Dialog)
            self.p126.setGeometry(QtCore.QRect(460, 800, 91, 101))
            self.p126.setText("")
            self.p126.setTextFormat(QtCore.Qt.RichText)
            self.p126.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Magmar_F.png"))
            self.p126.setObjectName("p126")
        if liste_pokemon[126].rencontre == True :
            self.p127 = QtWidgets.QLabel(Dialog)
            self.p127.setGeometry(QtCore.QRect(550, 800, 91, 101))
            self.p127.setText("")
            self.p127.setTextFormat(QtCore.Qt.RichText)
            self.p127.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Pinsir_F.png"))
            self.p127.setObjectName("p127")
        if liste_pokemon[127].rencontre == True :
            self.p128 = QtWidgets.QLabel(Dialog)
            self.p128.setGeometry(QtCore.QRect(640, 800, 91, 101))
            self.p128.setText("")
            self.p128.setTextFormat(QtCore.Qt.RichText)
            self.p128.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Tauros_F.png"))
            self.p128.setObjectName("128")
        if liste_pokemon[128].rencontre == True :
            self.p129 = QtWidgets.QLabel(Dialog)
            self.p129.setGeometry(QtCore.QRect(730, 800, 91, 101))
            self.p129.setText("")
            self.p129.setTextFormat(QtCore.Qt.RichText)
            self.p129.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Magikarp_F.png"))
            self.p129.setObjectName("129")
        if liste_pokemon[129].rencontre == True :
            self.p130 = QtWidgets.QLabel(Dialog)
            self.p130.setGeometry(QtCore.QRect(820, 800, 91, 101))
            self.p130.setText("")
            self.p130.setTextFormat(QtCore.Qt.RichText)
            self.p130.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Gyarados_F.png"))
            self.p130.setObjectName("p130")
        if liste_pokemon[130].rencontre == True :
            self.p131 = QtWidgets.QLabel(Dialog)
            self.p131.setGeometry(QtCore.QRect(910, 800, 91, 101))
            self.p131.setText("")
            self.p131.setTextFormat(QtCore.Qt.RichText)
            self.p131.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Lapras_F.png"))
            self.p131.setObjectName("p131")
        if liste_pokemon[131].rencontre == True :
            self.p132 = QtWidgets.QLabel(Dialog)
            self.p132.setGeometry(QtCore.QRect(1000, 800, 91, 101))
            self.p132.setText("")
            self.p132.setTextFormat(QtCore.Qt.RichText)
            self.p132.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Ditto_F.png"))
            self.p132.setObjectName("p132")
        if liste_pokemon[132].rencontre == True :
            self.p133 = QtWidgets.QLabel(Dialog)
            self.p133.setGeometry(QtCore.QRect(1090, 800, 91, 101))
            self.p133.setText("")
            self.p133.setTextFormat(QtCore.Qt.RichText)
            self.p133.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Eevee_F.png"))
            self.p133.setObjectName("p133")
        if liste_pokemon[133].rencontre == True :
            self.p134 = QtWidgets.QLabel(Dialog)
            self.p134.setGeometry(QtCore.QRect(1180, 800, 91, 101))
            self.p134.setText("")
            self.p134.setTextFormat(QtCore.Qt.RichText)
            self.p134.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Vaporeon_F.png"))
            self.p134.setObjectName("p134")
        if liste_pokemon[134].rencontre == True :
            self.p135 = QtWidgets.QLabel(Dialog)
            self.p135.setGeometry(QtCore.QRect(1270, 800, 91, 101))
            self.p135.setText("")
            self.p135.setTextFormat(QtCore.Qt.RichText)
            self.p135.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Jolteon_F.png"))
            self.p135.setObjectName("p135")
        if liste_pokemon[135].rencontre == True :
            self.p136 = QtWidgets.QLabel(Dialog)
            self.p136.setGeometry(QtCore.QRect(10, 900, 91, 101))
            self.p136.setText("")
            self.p136.setTextFormat(QtCore.Qt.RichText)
            self.p136.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Flareon_F.png"))
            self.p136.setObjectName("p136")
        if liste_pokemon[136].rencontre == True :
            self.p137 = QtWidgets.QLabel(Dialog)
            self.p137.setGeometry(QtCore.QRect(100, 900, 91, 101))
            self.p137.setText("")
            self.p137.setTextFormat(QtCore.Qt.RichText)
            self.p137.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Porygon_F.png"))
            self.p137.setObjectName("p137")
        if liste_pokemon[137].rencontre == True :
            self.p138 = QtWidgets.QLabel(Dialog)
            self.p138.setGeometry(QtCore.QRect(190, 900, 91, 101))
            self.p138.setText("")
            self.p138.setTextFormat(QtCore.Qt.RichText)
            self.p138.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Omanyte_F.png"))
            self.p138.setObjectName("p138")
        if liste_pokemon[138].rencontre == True :
            self.p139 = QtWidgets.QLabel(Dialog)
            self.p139.setGeometry(QtCore.QRect(280, 900, 91, 101))
            self.p139.setText("")
            self.p139.setTextFormat(QtCore.Qt.RichText)
            self.p139.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Omastar_F.png"))
            self.p139.setObjectName("p139")
        if liste_pokemon[139].rencontre == True :
            self.p140 = QtWidgets.QLabel(Dialog)
            self.p140.setGeometry(QtCore.QRect(370, 900, 91, 101))
            self.p140.setText("")
            self.p140.setTextFormat(QtCore.Qt.RichText)
            self.p140.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Kabuto_F.png"))
            self.p140.setObjectName("p140")
        if liste_pokemon[140].rencontre == True :
            self.p141 = QtWidgets.QLabel(Dialog)
            self.p141.setGeometry(QtCore.QRect(460, 900, 91, 101))
            self.p141.setText("")
            self.p141.setTextFormat(QtCore.Qt.RichText)
            self.p141.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Kabutops_F.png"))
            self.p141.setObjectName("p141")
        if liste_pokemon[141].rencontre == True :
            self.p142 = QtWidgets.QLabel(Dialog)
            self.p142.setGeometry(QtCore.QRect(550, 900, 91, 101))
            self.p142.setText("")
            self.p142.setTextFormat(QtCore.Qt.RichText)
            self.p142.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Aerodactyl_F.png"))
            self.p142.setObjectName("p142")
        if liste_pokemon[142].rencontre == True :
            self.p143 = QtWidgets.QLabel(Dialog)
            self.p143.setGeometry(QtCore.QRect(640, 900, 91, 101))
            self.p143.setText("")
            self.p143.setTextFormat(QtCore.Qt.RichText)
            self.p143.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Snorlax_F.png"))
            self.p143.setObjectName("p143")
        if liste_pokemon[143].rencontre == True :
            self.p144 = QtWidgets.QLabel(Dialog)
            self.p144.setGeometry(QtCore.QRect(730, 900, 91, 101))
            self.p144.setText("")
            self.p144.setTextFormat(QtCore.Qt.RichText)
            self.p144.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Articuno_F.png"))
            self.p144.setObjectName("p144")
        if liste_pokemon[144].rencontre == True :
            self.p145 = QtWidgets.QLabel(Dialog)
            self.p145.setGeometry(QtCore.QRect(820, 900, 91, 101))
            self.p145.setText("")
            self.p145.setTextFormat(QtCore.Qt.RichText)
            self.p145.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Zapdos_F.png"))
            self.p145.setObjectName("p145")
        if liste_pokemon[145].rencontre == True :
            self.p146 = QtWidgets.QLabel(Dialog)
            self.p146.setGeometry(QtCore.QRect(910, 900, 91, 101))
            self.p146.setText("")
            self.p146.setTextFormat(QtCore.Qt.RichText)
            self.p146.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Moltres_F.png"))
            self.p146.setObjectName("p146")
        if liste_pokemon[146].rencontre == True :
            self.p147 = QtWidgets.QLabel(Dialog)
            self.p147.setGeometry(QtCore.QRect(1000, 900, 91, 101))
            self.p147.setText("")
            self.p147.setTextFormat(QtCore.Qt.RichText)
            self.p147.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Dratini_F.png"))
            self.p147.setObjectName("p147")
        if liste_pokemon[147].rencontre == True :
            self.p148 = QtWidgets.QLabel(Dialog)
            self.p148.setGeometry(QtCore.QRect(1090, 900, 91, 101))
            self.p148.setText("")
            self.p148.setTextFormat(QtCore.Qt.RichText)
            self.p148.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Dragonair_F.png"))
            self.p148.setObjectName("p148")
        if liste_pokemon[148].rencontre == True :
            self.p149 = QtWidgets.QLabel(Dialog)
            self.p149.setGeometry(QtCore.QRect(1180, 900, 91, 101))
            self.p149.setText("")
            self.p149.setTextFormat(QtCore.Qt.RichText)
            self.p149.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Dragonite_F.png"))
            self.p149.setObjectName("p149")
        if liste_pokemon[149].rencontre == True :
            self.p150 = QtWidgets.QLabel(Dialog)
            self.p150.setGeometry(QtCore.QRect(1270, 900, 91, 101))
            self.p150.setText("")
            self.p150.setTextFormat(QtCore.Qt.RichText)
            self.p150.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Mewtwo_F.png"))
            self.p150.setObjectName("p150")
        if liste_pokemon[150].rencontre == True :
            self.p151 = QtWidgets.QLabel(Dialog)
            self.p151.setGeometry(QtCore.QRect(1360, 900, 91, 101))
            self.p151.setText("")
            self.p151.setTextFormat(QtCore.Qt.RichText)
            self.p151.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Mew_F.png"))
            self.p151.setObjectName("p151")
    

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        
        
class Window_poke(QMainWindow, Ui_Dialog):
    
    def __init__(self, parent = None):
        super(Window_poke, self).__init__(parent)
        self.setupUi(self)
    
    def keyPressEvent(self,event):
        
        if event.key()==Qt.Key_P:
            self.close()
            

def run_app():
    global poke_Win
    poke_Win = Window_poke()
    poke_Win.show()
