# -*- coding: utf-8 -*-
"""
Created on Mon May 13 15:53:20 2024

@author: anais
"""

#Import des Pokemons
from pokemons import liste_pokemon

pokedex = []

for i in range(151):
    pokedex.append(liste_pokemon[i].nom)
    
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QDialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(840, 781)
        self.p1 = QtWidgets.QLabel(Dialog)
        self.p1.setGeometry(QtCore.QRect(10, 0, 91, 101))
        self.p1.setText("")
        self.p1.setTextFormat(QtCore.Qt.RichText)
        self.p1.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Bulbasaur_F.png"))
        self.p1.setObjectName("p1")
        self.p2 = QtWidgets.QLabel(Dialog)
        self.p2.setGeometry(QtCore.QRect(100, 0, 91, 101))
        self.p2.setText("")
        self.p2.setTextFormat(QtCore.Qt.RichText)
        self.p2.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Ivysaur_F.png"))
        self.p2.setObjectName("p2")
        self.p3 = QtWidgets.QLabel(Dialog)
        self.p3.setGeometry(QtCore.QRect(190, 0, 91, 101))
        self.p3.setText("")
        self.p3.setTextFormat(QtCore.Qt.RichText)
        self.p3.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Venusaur_F.png"))
        self.p3.setObjectName("p3")
        self.p4 = QtWidgets.QLabel(Dialog)
        self.p4.setGeometry(QtCore.QRect(280, 0, 91, 101))
        self.p4.setText("")
        self.p4.setTextFormat(QtCore.Qt.RichText)
        self.p4.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Charmander_F.png"))
        self.p4.setObjectName("p4")
        self.p5 = QtWidgets.QLabel(Dialog)
        self.p5.setGeometry(QtCore.QRect(370, 0, 91, 101))
        self.p5.setText("")
        self.p5.setTextFormat(QtCore.Qt.RichText)
        self.p5.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Charmeleon_F.png"))
        self.p5.setObjectName("p5")
        self.p6 = QtWidgets.QLabel(Dialog)
        self.p6.setGeometry(QtCore.QRect(460, 0, 91, 101))
        self.p6.setText("")
        self.p6.setTextFormat(QtCore.Qt.RichText)
        self.p6.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Charizard_F.png"))
        self.p6.setObjectName("p6")
        self.p7 = QtWidgets.QLabel(Dialog)
        self.p7.setGeometry(QtCore.QRect(550, 0, 91, 101))
        self.p7.setText("")
        self.p7.setTextFormat(QtCore.Qt.RichText)
        self.p7.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Squirtle_F.png"))
        self.p7.setObjectName("p7")
        self.p8 = QtWidgets.QLabel(Dialog)
        self.p8.setGeometry(QtCore.QRect(640, 0, 91, 101))
        self.p8.setText("")
        self.p8.setTextFormat(QtCore.Qt.RichText)
        self.p8.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Wartortle_F.png"))
        self.p8.setObjectName("p8")
        self.p9 = QtWidgets.QLabel(Dialog)
        self.p9.setGeometry(QtCore.QRect(730, 0, 91, 101))
        self.p9.setText("")
        self.p9.setTextFormat(QtCore.Qt.RichText)
        self.p9.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Blastoise_F.png"))
        self.p9.setObjectName("p9")
        self.p10 = QtWidgets.QLabel(Dialog)
        self.p10.setGeometry(QtCore.QRect(10, 100, 91, 101))
        self.p10.setText("")
        self.p10.setTextFormat(QtCore.Qt.RichText)
        self.p10.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Caterpie_F.png"))
        self.p10.setObjectName("p10")
        self.p11 = QtWidgets.QLabel(Dialog)
        self.p11.setGeometry(QtCore.QRect(100, 100, 91, 101))
        self.p11.setText("")
        self.p11.setTextFormat(QtCore.Qt.RichText)
        self.p11.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Metapod_F.png"))
        self.p11.setObjectName("p11")
        self.p12 = QtWidgets.QLabel(Dialog)
        self.p12.setGeometry(QtCore.QRect(190, 100, 91, 101))
        self.p12.setText("")
        self.p12.setTextFormat(QtCore.Qt.RichText)
        self.p12.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Butterfree_F.png"))
        self.p12.setObjectName("p12")
        self.p13 = QtWidgets.QLabel(Dialog)
        self.p13.setGeometry(QtCore.QRect(280, 100, 91, 101))
        self.p13.setText("")
        self.p13.setTextFormat(QtCore.Qt.RichText)
        self.p13.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Weedle_F.png"))
        self.p13.setObjectName("p13")
        self.p14 = QtWidgets.QLabel(Dialog)
        self.p14.setGeometry(QtCore.QRect(370, 100, 91, 101))
        self.p14.setText("")
        self.p14.setTextFormat(QtCore.Qt.RichText)
        self.p14.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Kakuna_F.png"))
        self.p14.setObjectName("p14")
        self.p15 = QtWidgets.QLabel(Dialog)
        self.p15.setGeometry(QtCore.QRect(370, 100, 91, 101))
        self.p15.setText("")
        self.p15.setTextFormat(QtCore.Qt.RichText)
        self.p15.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Beedrill_F.png"))
        self.p15.setObjectName("p15")
        self.p16 = QtWidgets.QLabel(Dialog)
        self.p16.setGeometry(QtCore.QRect(460, 100, 91, 101))
        self.p16.setText("")
        self.p16.setTextFormat(QtCore.Qt.RichText)
        self.p16.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Pidgey_F.png"))
        self.p16.setObjectName("p16")
        self.p17 = QtWidgets.QLabel(Dialog)
        self.p17.setGeometry(QtCore.QRect(550, 100, 91, 101))
        self.p17.setText("")
        self.p17.setTextFormat(QtCore.Qt.RichText)
        self.p17.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Pidgeotto_F.png"))
        self.p17.setObjectName("p17")
        self.p18 = QtWidgets.QLabel(Dialog)
        self.p18.setGeometry(QtCore.QRect(640, 100, 91, 101))
        self.p18.setText("")
        self.p18.setTextFormat(QtCore.Qt.RichText)
        self.p18.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Pidgeot_F.png"))
        self.p18.setObjectName("p18")
        self.p19 = QtWidgets.QLabel(Dialog)
        self.p19.setGeometry(QtCore.QRect(730, 100, 91, 101))
        self.p19.setText("")
        self.p19.setTextFormat(QtCore.Qt.RichText)
        self.p19.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Rattata_F.png"))
        self.p19.setObjectName("p19")
        self.p20 = QtWidgets.QLabel(Dialog)
        self.p20.setGeometry(QtCore.QRect(10, 200, 91, 101))
        self.p20.setText("")
        self.p20.setTextFormat(QtCore.Qt.RichText)
        self.p20.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Raticate_F.png"))
        self.p20.setObjectName("p20")
        self.p21 = QtWidgets.QLabel(Dialog)
        self.p21.setGeometry(QtCore.QRect(100, 200, 91, 101))
        self.p21.setText("")
        self.p21.setTextFormat(QtCore.Qt.RichText)
        self.p21.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Spearow_F.png"))
        self.p21.setObjectName("p21")
        self.p22 = QtWidgets.QLabel(Dialog)
        self.p22.setGeometry(QtCore.QRect(190, 200, 91, 101))
        self.p22.setText("")
        self.p22.setTextFormat(QtCore.Qt.RichText)
        self.p22.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Fearow_F.png"))
        self.p22.setObjectName("p22")
        self.p23 = QtWidgets.QLabel(Dialog)
        self.p23.setGeometry(QtCore.QRect(280, 200, 91, 101))
        self.p23.setText("")
        self.p23.setTextFormat(QtCore.Qt.RichText)
        self.p23.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Ekans_F.png"))
        self.p23.setObjectName("p23")
        self.p24 = QtWidgets.QLabel(Dialog)
        self.p24.setGeometry(QtCore.QRect(370, 200, 91, 101))
        self.p24.setText("")
        self.p24.setTextFormat(QtCore.Qt.RichText)
        self.p24.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Arbok_F.png"))
        self.p24.setObjectName("p24")
        self.p25 = QtWidgets.QLabel(Dialog)
        self.p25.setGeometry(QtCore.QRect(460, 200, 91, 101))
        self.p25.setText("")
        self.p25.setTextFormat(QtCore.Qt.RichText)
        self.p25.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Pikachu_F.png"))
        self.p25.setObjectName("p25")
        self.p26 = QtWidgets.QLabel(Dialog)
        self.p26.setGeometry(QtCore.QRect(550, 200, 91, 101))
        self.p26.setText("")
        self.p26.setTextFormat(QtCore.Qt.RichText)
        self.p26.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Raichu_F.png"))
        self.p26.setObjectName("p26")
        self.p27 = QtWidgets.QLabel(Dialog)
        self.p27.setGeometry(QtCore.QRect(640, 200, 91, 101))
        self.p27.setText("")
        self.p27.setTextFormat(QtCore.Qt.RichText)
        self.p27.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Sandshrew_F.png"))
        self.p27.setObjectName("p27")
        self.p28 = QtWidgets.QLabel(Dialog)
        self.p28.setGeometry(QtCore.QRect(730, 200, 91, 101))
        self.p28.setText("")
        self.p28.setTextFormat(QtCore.Qt.RichText)
        self.p28.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Sandslash_F.png"))
        self.p28.setObjectName("p28")
        self.p29 = QtWidgets.QLabel(Dialog)
        self.p29.setGeometry(QtCore.QRect(10, 300, 91, 101))
        self.p29.setText("")
        self.p29.setTextFormat(QtCore.Qt.RichText)
        self.p29.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidoran♀_F.png"))
        self.p29.setObjectName("p29")
        self.p30 = QtWidgets.QLabel(Dialog)
        self.p30.setGeometry(QtCore.QRect(100, 300, 91, 101))
        self.p30.setText("")
        self.p30.setTextFormat(QtCore.Qt.RichText)
        self.p30.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidorina_F.png"))
        self.p30.setObjectName("p30")
        self.p31 = QtWidgets.QLabel(Dialog)
        self.p31.setGeometry(QtCore.QRect(190, 300, 91, 101))
        self.p31.setText("")
        self.p31.setTextFormat(QtCore.Qt.RichText)
        self.p31.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidoqueen_F.png"))
        self.p31.setObjectName("p31")
        self.p32 = QtWidgets.QLabel(Dialog)
        self.p32.setGeometry(QtCore.QRect(280, 300, 91, 101))
        self.p32.setText("")
        self.p32.setTextFormat(QtCore.Qt.RichText)
        self.p32.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidoran♂_F.png"))
        self.p32.setObjectName("p32")
        self.p33 = QtWidgets.QLabel(Dialog)
        self.p33.setGeometry(QtCore.QRect(370, 300, 91, 101))
        self.p33.setText("")
        self.p33.setTextFormat(QtCore.Qt.RichText)
        self.p33.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidorino_F.png"))
        self.p33.setObjectName("p33")
        self.p34 = QtWidgets.QLabel(Dialog)
        self.p34.setGeometry(QtCore.QRect(460, 300, 91, 101))
        self.p34.setText("")
        self.p34.setTextFormat(QtCore.Qt.RichText)
        self.p34.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Nidoking_F.png"))
        self.p34.setObjectName("p34")
        self.p35 = QtWidgets.QLabel(Dialog)
        self.p35.setGeometry(QtCore.QRect(550, 300, 91, 101))
        self.p35.setText("")
        self.p35.setTextFormat(QtCore.Qt.RichText)
        self.p35.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Clefairy_F.png"))
        self.p35.setObjectName("p35")
        self.p36 = QtWidgets.QLabel(Dialog)
        self.p36.setGeometry(QtCore.QRect(640, 300, 91, 101))
        self.p36.setText("")
        self.p36.setTextFormat(QtCore.Qt.RichText)
        self.p36.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Clefable_F.png"))
        self.p36.setObjectName("p36")
        self.p37 = QtWidgets.QLabel(Dialog)
        self.p37.setGeometry(QtCore.QRect(730, 300, 91, 101))
        self.p37.setText("")
        self.p37.setTextFormat(QtCore.Qt.RichText)
        self.p37.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Vulpix_F.png"))
        self.p37.setObjectName("p37")
        self.p38 = QtWidgets.QLabel(Dialog)
        self.p38.setGeometry(QtCore.QRect(10, 400, 91, 101))
        self.p38.setText("")
        self.p38.setTextFormat(QtCore.Qt.RichText)
        self.p38.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Ninetales_F.png"))
        self.p38.setObjectName("38")
        self.p39 = QtWidgets.QLabel(Dialog)
        self.p39.setGeometry(QtCore.QRect(100, 400, 91, 101))
        self.p39.setText("")
        self.p39.setTextFormat(QtCore.Qt.RichText)
        self.p39.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Jigglypuff_F.png"))
        self.p39.setObjectName("39")
        self.p40 = QtWidgets.QLabel(Dialog)
        self.p40.setGeometry(QtCore.QRect(190, 400, 91, 101))
        self.p40.setText("")
        self.p40.setTextFormat(QtCore.Qt.RichText)
        self.p40.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Wigglytuff_F.png"))
        self.p40.setObjectName("p40")
        self.p41 = QtWidgets.QLabel(Dialog)
        self.p41.setGeometry(QtCore.QRect(280, 400, 91, 101))
        self.p41.setText("")
        self.p41.setTextFormat(QtCore.Qt.RichText)
        self.p41.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Zubat_F.png"))
        self.p41.setObjectName("p41")
        self.p42 = QtWidgets.QLabel(Dialog)
        self.p42.setGeometry(QtCore.QRect(370, 400, 91, 101))
        self.p42.setText("")
        self.p42.setTextFormat(QtCore.Qt.RichText)
        self.p42.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Golbat_F.png"))
        self.p42.setObjectName("p42")
        self.p43 = QtWidgets.QLabel(Dialog)
        self.p43.setGeometry(QtCore.QRect(460, 400, 91, 101))
        self.p43.setText("")
        self.p43.setTextFormat(QtCore.Qt.RichText)
        self.p43.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Oddish_F.png"))
        self.p43.setObjectName("p43")
        self.p44 = QtWidgets.QLabel(Dialog)
        self.p44.setGeometry(QtCore.QRect(550, 400, 91, 101))
        self.p44.setText("")
        self.p44.setTextFormat(QtCore.Qt.RichText)
        self.p44.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Gloom_F.png"))
        self.p44.setObjectName("p44")
        self.p45 = QtWidgets.QLabel(Dialog)
        self.p45.setGeometry(QtCore.QRect(640, 400, 91, 101))
        self.p45.setText("")
        self.p45.setTextFormat(QtCore.Qt.RichText)
        self.p45.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Vileplume_F.png"))
        self.p45.setObjectName("p45")
        self.p46 = QtWidgets.QLabel(Dialog)
        self.p46.setGeometry(QtCore.QRect(730, 400, 91, 101))
        self.p46.setText("")
        self.p46.setTextFormat(QtCore.Qt.RichText)
        self.p46.setPixmap(QtGui.QPixmap("data/pokemon_sprite/Paras_F.png"))
        self.p46.setObjectName("p46")
        

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        
        
class Window(QMainWindow, Ui_Dialog):
    
    def __init__(self, parent = None):
        super(Window, self).__init__(parent)
        self.setupUi(self)


def run_app():
    app = QApplication(sys.argv)
    mainWin = Window()
    mainWin.show()
    app.exec_()
    
    
run_app()